import type { Metadata } from "next";
import "./globals.css";
import {initializeDataSource} from "@/backend/config/datasource";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({  children}: Readonly<{ children: React.ReactNode; }>) {
    const isConnected = await initializeDataSource(); // Ensure DB is initialized

    if (!isConnected) {
        return (
            <html lang="en">
            <body>
            <h1>Error</h1>
            <p>Failed to connect to the database. Please try again later.</p>
            </body>
            </html>
        );
    }

    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    );
}
